//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package res

import (
	"KryptonGo/pkg/luban"
	"errors"
)

type ByteBufLoader func(string) (*luban.ByteBuf, error)

type Tables struct {
	TbReward *TbReward
}

func NewTables(loader ByteBufLoader) (*Tables, error) {
	var err error
	var buf *luban.ByteBuf

	tables := &Tables{}
	if buf, err = loader("tbreward"); err != nil {
		return nil, err
	}
	if tables.TbReward, err = NewTbReward(buf); err != nil {
		return nil, errors.Join(errors.New("failed to load TbReward"), err)
	}
	return tables, nil
}
