
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package res;


import "KryptonGo/pkg/luban"

type TbReward struct {
    _dataMap map[int32]*Reward
    _dataList []*Reward
}

func NewTbReward(_buf *luban.ByteBuf) (*TbReward, error) {
	if size, err := _buf.ReadSize() ; err != nil {
		return nil, err
	} else {
		_dataList := make([]*Reward, 0, size)
		dataMap := make(map[int32]*Reward)

		for i := 0 ; i < size ; i++ {
			if _v, err2 := NewReward(_buf); err2 != nil {
				return nil, err2
			} else {
				_dataList = append(_dataList, _v)
				dataMap[_v.Id] = _v
			}
		}
		return &TbReward{_dataList:_dataList, _dataMap:dataMap}, nil
	}
}

func (table *TbReward) GetDataMap() map[int32]*Reward {
    return table._dataMap
}

func (table *TbReward) GetDataList() []*Reward {
    return table._dataList
}

func (table *TbReward) Get(key int32) *Reward {
    return table._dataMap[key]
}


